# Site settings
title: GSoC 2017, poetry, stuff.
description: Here, I write about what I am currently doing for my GSoC Project, or any poetry, short shayaries (funny, sometimes ;P)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rj722.tech" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rahul Jha
user_description: Engineering Student, Python Developer, Learning Data Science
user_title: Software Developer, Loves Testing
email: rahul722j@gmail.com
twitter_username: RJ722
github_username:  RJ722
gplus_username:  Rahul Jha
disqus_username: RJ722

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: https://rj722.tech
    external: true
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
