# Site settings
title: A blog where I write sometimes.
description: What I am currently doing, my plans for GSoC Project, or any poetry/ short shayaries, project descriptions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rj722.tech" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rahul Jha
user_description: Developer @vulture and @coala, @GSoC 2017
user_title: Software Developer @vulture, @coala
email: rahul@rj722.tech
twitter_username: rahul722j
github_username: RJ722
gplus_username: +RahulJha722
disqus_username: RJ722

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
